name: Sync product labels
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: joeyparrish/action-label-syncer@rename-and-import
      # - uses: micnncim/action-label-syncer@v1
        with:
          manifest: labels/labels-product.yml
          repository: |
            bu-ist/bu-banners
            bu-ist/bu-blocks
            bu-ist/bu-filtering
            bu-ist/bu-landing-pages
            bu-ist/bu-prepress
            bu-ist/bu-program-pages
            bu-ist/bu-responsive-customizations
            bu-ist/bu-stats
            bu-ist/bu-timeline
            bu-ist/cdn
            bu-ist/responsive-child-starter
            bu-ist/responsive-child-starter-3x
            bu-ist/responsive-foundation
            bu-ist/responsive-framework
            bu-ist/responsive-framework-3x
            bu-ist/bu-announcements
            bu-ist/id-gutenberg
            bu-ist/bu-block-starter
            bu-ist/responsive-child-starter-3x-block-editor
            bu-ist/bu-testimonials
            bu-ist/bu-policy-links
          token: ${{ secrets.PERSONAL_TOKEN }}
          prune: false
